id: IB5988FF8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T14:04:08+00:00'
last_modified: '2022-06-08T10:57:37.473183+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15365
  title: ཏིབེཏན་མནུསཅྲིཔཙ་ཨནད་བློཅཀཔྲིནཙ་ཨིན་ཐེ་ལིབྲརཡ་ཨོཕ༹་ཐེ་ཨོརིཨེནཏལ་ཨིནསྟིཏུཏེ་པྲགུཨེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CFF2:
      image_group_id: I1KG15391
      title: Volume 1 of tibetan manuscripts and blockprints in the library of the
        oriental institute prague
      total_pages: 126
      order: 1
      base_file: CFF2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
