id: opecha:P006999
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15365
  title: ཏིབེཏན་མནུསཅྲིཔཙ་ཨནད་བློཅཀཔྲིནཙ་ཨིན་ཐེ་ལིབྲརཡ་ཨོཕ༹་ཐེ་ཨོརིཨེནཏལ་ཨིནསྟིཏུཏེ་པྲགུཨེ
  volume: ''
  author: ''
