id: P006999
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15365
  title: ཏིབེཏན་མནུསཅྲིཔཙ་ཨནད་བློཅཀཔྲིནཙ་ཨིན་ཐེ་ལིབྲརཡ་ཨོཕ༹་ཐེ་ཨོརིཨེནཏལ་ཨིནསྟིཏུཏེ་པྲགུཨེ
  author: ''
  volumes:
    cce4cfecb3b047f9bb16ede8f74b5faa:
      image_group_id: I1KG15391
      title: ''
      volume_number: 1
      total_pages: 126
ebook_metadata:
  title: ཏིབེཏན་མནུསཅྲིཔཙ་ཨནད་བློཅཀཔྲིནཙ་ཨིན་ཐེ་ལིབྲརཡ་ཨོཕ༹་ཐེ་ཨོརིཨེནཏལ་ཨིནསྟིཏུཏེ་པྲགུཨེ
  author: ''
  sku: P006999
  cover: cover.jpg
  layers:
  - pagination
